language: haskell
ghc: 7.10

install:
  - cabal install --only-dependencies --enable-tests
  - cabal install QuickCheck hspec

script:
  - cabal configure --enable-tests && cabal build
  - run-cabal-test --show-details=always

branches:
  only:
    - master
